# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afterwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.IntegerField(choices=[(0, '小王'), (1, '小张')], verbose_name='收拾')),
                ('fruit', models.IntegerField(choices=[(0, '没有水果吃'), (1, '买水果吃')], verbose_name='餐后水果')),
            ],
            options={
                'verbose_name': '餐后工作',
                'verbose_name_plural': '餐后工作',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='菜名')),
                ('type', models.IntegerField(choices=[(0, '荤'), (1, '素')], verbose_name='类型')),
                ('cooker', models.IntegerField(choices=[(0, '小王'), (1, '小张')], verbose_name='谁做')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
    ]
